# Generated by Django 4.2.5 on 2023-09-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="family_members",
            name="password",
            field=models.CharField(null=True),
        ),
    ]
