# Generated by Django 4.2.5 on 2023-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0002_family_members_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="family_members",
            name="fullname",
            field=models.CharField(
                default="<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>"
            ),
        ),
    ]
