# Generated by Django 4.2.5 on 2023-09-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0003_family_members_fullname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="family_members",
            name="fullname",
        ),
        migrations.AddField(
            model_name="family_members",
            name="username",
            field=models.CharField(null=True),
        ),
    ]
