# Generated by Django 4.2.5 on 2023-10-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0004_remove_family_members_fullname_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Family_members",
        ),
    ]
