# Generated by Django 4.2.5 on 2023-10-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("test_website", "0005_delete_family_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="cat_pics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.TextField()),
            ],
        ),
    ]
