# Generated by Django 4.2.5 on 2023-10-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0006_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat_pics",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
