# Generated by Django 4.2.5 on 2023-10-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0008_remove_cat_pics_likes_remove_cat_pics_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat_pics",
            name="image",
            field=models.ImageField(default="", upload_to="test_website/images/cats"),
        ),
    ]
