# Generated by Django 4.2.5 on 2023-10-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0009_alter_cat_pics_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="cat_pics",
            new_name="cat_pic",
        ),
    ]
