# Generated by Django 4.2.5 on 2023-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0010_rename_cat_pics_cat_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat_pic",
            name="image",
            field=models.ImageField(
                default="",
                upload_to="test_website/images/cats<django.db.models.fields.CharField>",
            ),
        ),
        migrations.AlterField(
            model_name="cat_pic",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
