# Generated by Django 4.2.5 on 2023-11-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0011_alter_cat_pic_image_alter_cat_pic_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cat_pic",
            name="image",
        ),
    ]
