# Generated by Django 4.2.5 on 2023-11-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0012_remove_cat_pic_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="post_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_website.cat_pic",
                    ),
                ),
            ],
        ),
    ]
