# Generated by Django 4.2.5 on 2023-11-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0013_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat_pic",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="cat_pic",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="post_image",
            name="images",
            field=models.ImageField(
                default=None, upload_to="test_website/images/cats/%Y-%m/%Y-%m-%d"
            ),
        ),
    ]
