# Generated by Django 4.2.5 on 2023-11-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0014_cat_pic_description_cat_pic_image_post_image_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post_image",
            name="post",
        ),
    ]
