# Generated by Django 4.2.5 on 2023-11-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0015_remove_post_image_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat_pic",
            name="image",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="test_website.post_image",
            ),
        ),
    ]
