# Generated by Django 4.2.5 on 2023-11-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0016_alter_cat_pic_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat_pic",
            name="upload_date",
            field=models.DateTimeField(default=None),
        ),
    ]
