# Generated by Django 4.2.5 on 2023-11-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_website", "0017_cat_pic_upload_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeStampMixin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="cat_pic",
            name="upload_date",
        ),
        migrations.AddField(
            model_name="cat_pic",
            name="dates",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="test_website.timestampmixin",
            ),
        ),
    ]
